/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Crumb } from "./components/modus-breadcrumb/modus-breadcrumb";
import { App } from "./components/modus-navbar/apps-menu/modus-navbar-apps-menu";
import { App as App1 } from "./components/modus-navbar/apps-menu/modus-navbar-apps-menu";
import { RadioButton } from "./components/modus-radio-group/modus-radio-button";
import { Tab } from "./components/modus-tabs/modus-tabs";
export namespace Components {
    interface ModusAccordion {
        /**
          * (optional) The accordion's aria-label.
         */
        "ariaLabel": string;
    }
    interface ModusAccordionItem {
        /**
          * (optional) Disables the accordion item, locks expand/collapse.
         */
        "disabled": boolean;
        /**
          * (optional) Whether the accordion item is expanded.
         */
        "expanded": boolean;
        /**
          * (required) The text to render in the header.
         */
        "headerText": string;
        /**
          * (optional) The size of accordion item.
         */
        "size": 'condensed' | 'standard';
    }
    interface ModusAlert {
        /**
          * (optional) The alert's aria-label.
         */
        "ariaLabel": string;
        /**
          * (optional) Whether the alert has a dismiss button
         */
        "dismissible": boolean;
        /**
          * (optional) The alert message
         */
        "message": string;
        /**
          * (optional) The type of alert, sets the color and icon to render
         */
        "type": 'error' | 'info' | 'info-gray' | 'info-gray-dark' | 'success' | 'warning';
    }
    interface ModusBadge {
        /**
          * (optional) The badge's aria-label
         */
        "ariaLabel": string;
        /**
          * (optional) The color of the badge
         */
        "color": 'danger' | 'dark' | 'primary' | 'secondary' | 'success' | 'tertiary' | 'warning';
        /**
          * (optional) The size of the badge
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * (optional) The type of the badge
         */
        "type": 'counter' | 'default' | 'text';
    }
    interface ModusBreadcrumb {
        /**
          * The breadcrumb's aria-label.
         */
        "ariaLabel": string;
        /**
          * The breadcrumbs to render.
         */
        "crumbs": Crumb[];
    }
    interface ModusButton {
        /**
          * (optional) The button's aria-label.
         */
        "ariaLabel": string;
        /**
          * (optional) The style of the button
         */
        "buttonStyle": 'borderless' | 'fill' | 'outline';
        /**
          * (optional) The color of the button.
         */
        "color": 'danger' | 'default' | 'primary' | 'secondary' | 'warning';
        /**
          * (optional) Disables the button.
         */
        "disabled": boolean;
        /**
          * (optional) The size of the button.
         */
        "size": 'small' | 'medium' | 'large';
    }
    interface ModusCard {
        /**
          * (optional) The card's aria-label.
         */
        "ariaLabel": string;
        /**
          * (optional) The height of the card.
         */
        "height": string;
        /**
          * (optional) The width of the card.
         */
        "width": string;
    }
    interface ModusCheckbox {
        /**
          * (optional) The checkbox's aria-label.
         */
        "ariaLabel": string;
        /**
          * (optional) Whether the checkbox is checked.
         */
        "checked": boolean;
        /**
          * (optional) Whether the checkbox is disabled.
         */
        "disabled": boolean;
        /**
          * (optional) Whether the checkbox is indeterminate.
         */
        "indeterminate": boolean;
        /**
          * (optional) The checkbox label.
         */
        "label": string;
        /**
          * (optional) The size of the button
         */
        "size": 'small' | 'medium';
    }
    interface ModusChip {
        /**
          * (optional) The chip's aria-label.
         */
        "ariaLabel": string;
        /**
          * (optional) The chip's style.
         */
        "chipStyle": 'outline' | 'solid';
        /**
          * (optional) Whether the chip is disabled.
         */
        "disabled": boolean;
        /**
          * (optional) Whether the chip has an error.
         */
        "hasError": boolean;
        /**
          * (optional) The image's url.
         */
        "imageUrl": string;
        /**
          * (optional) Whether to show the checkmark.
         */
        "showCheckmark": boolean;
        /**
          * (optional) Whether to show the close icon.
         */
        "showClose": boolean;
        /**
          * (optional) The chip's size.
         */
        "size": 'medium' | 'large';
        /**
          * (optional) The chip's value.
         */
        "value": string;
    }
    interface ModusDropdown {
        /**
          * (optional) The dropdown's aria-label.
         */
        "ariaLabel": string;
        /**
          * (optional) Disables the dropdown.
         */
        "disabled": boolean;
        /**
          * (optional) The placement of the dropdown in related to the toggleElement.
         */
        "placement": 'top' | 'right' | 'bottom' | 'left';
        /**
          * (required) The element id that the list renders near and that triggers the toggling of the list.
         */
        "toggleElementId": string;
    }
    interface ModusFileDropzone {
        /**
          * Add a file to the dropzone.
         */
        "addFile": (file: File) => Promise<void>;
        /**
          * (optional) The dropzone's aria-label.
         */
        "ariaLabel": string;
        /**
          * (optional) The dropzone's description text.
         */
        "description": string;
        /**
          * (optional) The dropzone's height.
         */
        "dropzoneHeight": string;
        /**
          * (optional) The dropzone's width.
         */
        "dropzoneWidth": string;
        /**
          * Get the dropzone's error.
         */
        "getError": () => Promise<string | null>;
        /**
          * Get the dropzone's files.
         */
        "getFiles": () => Promise<File[]>;
        /**
          * (optional) Whether to include the upload icon.
         */
        "includeStateIcon": boolean;
        /**
          * (optional) The dropzone's label text.
         */
        "label": string;
        /**
          * (optional) The dropzone's max file count.
         */
        "maxFileCount": number;
        /**
          * (optional) The dropzone's max file name length of each file.
         */
        "maxFileNameLength": number;
        /**
          * (optional) The dropzone's max total file size.
         */
        "maxTotalFileSizeBytes": number;
        /**
          * (optional) Whether multiple files can be uploaded.
         */
        "multiple": boolean;
        /**
          * Remove a file from the dropzone.
         */
        "removeFile": (fileName: string) => Promise<void>;
    }
    interface ModusList {
    }
    interface ModusListItem {
        /**
          * (optional) Disables the list item
         */
        "disabled": boolean;
        /**
          * (optional) The selected state of the list item
         */
        "selected": boolean;
        /**
          * (optional) The size of list item
         */
        "size": 'condensed' | 'large' | 'standard';
        /**
          * (optional) The type of list item
         */
        "type": 'standard';
    }
    interface ModusMessage {
        /**
          * (optional) The message's aria-label.
         */
        "ariaLabel": string;
        /**
          * (optional) The message's type.
         */
        "type": 'info' | 'question';
    }
    interface ModusModal {
        /**
          * (optional) The modal's aria-label.
         */
        "ariaLabel": string;
        "close": () => Promise<void>;
        /**
          * (optional) The modal's primary button text.
         */
        "headerText": string;
        "open": () => Promise<void>;
        /**
          * (optional) The modal's primary button text.
         */
        "primaryButtonText": string;
        /**
          * (optional) The modal's secondary button text.
         */
        "secondaryButtonText": string;
        /**
          * (optional) The modal's z-index.
         */
        "zIndex": string;
    }
    interface ModusNavbar {
        /**
          * (optional) The apps to render in the apps menu.
         */
        "apps": App[];
        "hideMainMenu": () => Promise<void>;
        /**
          * (required) Product logo options.
         */
        "productLogoOptions": { height?: string; url: string };
        /**
          * (required) Profile menu options.
         */
        "profileMenuOptions": { avatarUrl?: string, email?: string, initials?: string, username: string };
        /**
          * (optional) Whether to display the navbar items in reverse order.
         */
        "reverse": boolean;
        /**
          * (optional) Whether to show the apps menu.
         */
        "showAppsMenu": boolean;
        /**
          * (optional) Whether to show the main menu.
         */
        "showMainMenu": boolean;
        /**
          * (optional) Whether to show notifications.
         */
        "showNotifications": boolean;
        /**
          * (optional) Whether to show the placeholder for Pendo.
         */
        "showPendoPlaceholder": boolean;
        /**
          * (optional) Whether to show search.
         */
        "showSearch": boolean;
        /**
          * (optional) Whether to show a shadow under the navbar.
         */
        "showShadow": boolean;
    }
    interface ModusNavbarAppsMenu {
        "apps": App[];
        "reverse": boolean;
    }
    interface ModusNavbarMainMenu {
    }
    interface ModusNavbarNotificationsMenu {
        "reverse": boolean;
    }
    interface ModusNavbarProfileMenu {
        "avatarUrl": string;
        "email": string;
        "initials": string;
        "reverse": boolean;
        "username": string;
    }
    interface ModusNumberInput {
        /**
          * (optional) The input's aria-label.
         */
        "ariaLabel": string;
        /**
          * (optional) Whether the input is disabled.
         */
        "disabled": boolean;
        /**
          * (optional) The input's error state text.
         */
        "errorText": string;
        /**
          * (optional) The input's helper text displayed below the input.
         */
        "helperText": string;
        /**
          * (optional) The input's label.
         */
        "label": string;
        /**
          * (optional) The input's maximum value.
         */
        "maxValue": number;
        /**
          * (optional) The input's minimum value.
         */
        "minValue": number;
        /**
          * (optional) The input's placeholder text.
         */
        "placeholder": string;
        /**
          * (optional) Whether the input's content is read-only
         */
        "readOnly": boolean;
        /**
          * (optional) Whether the input is required.
         */
        "required": boolean;
        /**
          * (optional) The input's size.
         */
        "size": 'medium' | 'large';
        /**
          * (optional) The input's step.
         */
        "step": number;
        /**
          * (optional) The input's valid state text.
         */
        "validText": string;
        /**
          * (optional) The input's value.
         */
        "value": string;
    }
    interface ModusPagination {
        "activePage": number;
        "ariaLabel": string;
        "maxPage": number;
        "minPage": number;
        "size": 'large' | 'medium' | 'small';
    }
    interface ModusProgressBar {
        /**
          * (optional) The progress bar's aria-label.
         */
        "ariaLabel": string;
        /**
          * (optional) The progress bar's background color.
         */
        "backgroundColor": string;
        /**
          * (optional) The progress bar's foreground color.
         */
        "color": string;
        /**
          * (optional) The progress bar's maximum value.
         */
        "maxValue": number;
        /**
          * (optional) The progress bar's minimum value.
         */
        "minValue": number;
        /**
          * (optional) The progress bar's size.
         */
        "size": 'default' | 'compact';
        /**
          * (optional) The text displayed on the progress bar.
         */
        "text": string;
        /**
          * (optional) The progress bar's text color.
         */
        "textColor": string;
        /**
          * (optional) The progress bar's value.
         */
        "value": number;
    }
    interface ModusRadioGroup {
        /**
          * The radio group's aria-label.
         */
        "ariaLabel": string;
        /**
          * The ID of the checked radio button.
         */
        "checkedId": string;
        /**
          * The radio button group name.
         */
        "name": string;
        /**
          * The radio buttons to render.
         */
        "radioButtons": RadioButton[];
    }
    interface ModusSelect {
        /**
          * (optional) The select's aria-label.
         */
        "ariaLabel": string;
        /**
          * (optional) Whether the input is disabled.
         */
        "disabled": boolean;
        /**
          * (optional) The input's error text.
         */
        "errorText": string;
        /**
          * (optional) The input's helper text.
         */
        "helperText": string;
        /**
          * (optional) The input label.
         */
        "label": string;
        /**
          * The options for the dropdown list.
         */
        "options": unknown[];
        /**
          * The options property to render in the dropdown list.
         */
        "optionsDisplayProp": string;
        /**
          * (optional) Whether the input is required.
         */
        "required": boolean;
        /**
          * (optional) The input's size.
         */
        "size": 'medium' | 'large';
        /**
          * (optional) The input's valid text.
         */
        "validText": string;
        /**
          * (optional) The input value.
         */
        "value": unknown;
    }
    interface ModusSlider {
        /**
          * (optional) The slider's aria-label.
         */
        "ariaLabel": string;
        /**
          * (optional) Whether the slider is disabled. *
         */
        "disabled": boolean;
        /**
          * (optional) The slider's label.
         */
        "label": string;
        /**
          * (optional) The slider's maximum value.
         */
        "maxValue": number;
        /**
          * (optional) The slider's minimum value.
         */
        "minValue": number;
        /**
          * (optional) The slider's value.
         */
        "value": string;
    }
    interface ModusSpinner {
        /**
          * (optional) The color of the spinner in hex format (eg #FFFFFF)
         */
        "color": string;
        /**
          * (optional) The size of the spinner, will be applied to both the height and width
         */
        "size": string;
    }
    interface ModusSwitch {
        /**
          * (optional) The switch's aria-label.
         */
        "ariaLabel": string;
        /**
          * (optional) Whether the switch is checked.
         */
        "checked": boolean;
        /**
          * (optional) Whether the switch is disabled.
         */
        "disabled": boolean;
        /**
          * (optional) The switch label.
         */
        "label": string;
    }
    interface ModusTabs {
        "ariaLabel": string;
        "size": 'medium' | 'small';
        /**
          * The tabs to render.
         */
        "tabs": Tab[];
    }
    interface ModusTextInput {
        /**
          * (optional) The input's aria-label.
         */
        "ariaLabel": string;
        /**
          * (optional) Whether the input has a clear button.
         */
        "clearable": boolean;
        /**
          * (optional) Whether the input is disabled.
         */
        "disabled": boolean;
        /**
          * (optional) The input's error state text.
         */
        "errorText": string;
        /**
          * (optional) The input's helper text displayed below the input.
         */
        "helperText": string;
        /**
          * (optional) Whether the search icon is included.
         */
        "includeSearchIcon": boolean;
        /**
          * (optional) The input's inputmode.
         */
        "inputmode": 'decimal' | 'email' | 'numeric' | 'search' | 'tel' | 'text' | 'url';
        /**
          * (optional) The input's label.
         */
        "label": string;
        /**
          * (optional) The input's maximum length.
         */
        "maxLength": number;
        /**
          * (optional) The input's minimum length.
         */
        "minLength": number;
        /**
          * (optional) The input's placeholder text.
         */
        "placeholder": string;
        /**
          * (optional) Whether the input's content is read-only
         */
        "readOnly": boolean;
        /**
          * (optional) Whether the input is required.
         */
        "required": boolean;
        /**
          * (optional) The input's size.
         */
        "size": 'medium' | 'large';
        /**
          * (optional) The input's type.
         */
        "type": 'text' | 'password';
        /**
          * (optional) The input's valid state text.
         */
        "validText": string;
        /**
          * (optional) The input's value.
         */
        "value": string;
    }
    interface ModusToast {
        /**
          * (optional) The toast's aria-label.
         */
        "ariaLabel": string;
        /**
          * (optional) Whether the toast has a dismiss button.
         */
        "dismissible": boolean;
        /**
          * (optional) Whether to show the toasts' icon.
         */
        "showIcon": boolean;
        /**
          * (optional) The toasts' type.
         */
        "type": 'danger' | 'dark' | 'default' | 'primary' | 'secondary' | 'success' | 'tertiary' | 'warning';
    }
    interface ModusTooltip {
        /**
          * (optional) The tooltip's aria-label.
         */
        "ariaLabel": string;
        /**
          * (optional) The tooltip's position relative to its content.
         */
        "position": 'bottom' | 'left' | 'right' | 'top';
        /**
          * The tooltip's text.
         */
        "text": string;
    }
    interface ModusTreeView {
        /**
          * (optional) Enables checkbox selection on each tree item
         */
        "checkboxSelection": boolean;
        /**
          * (optional) Disables each tree item
         */
        "disabled": boolean;
        /**
          * (optional) Enables multiple checkbox selection
         */
        "multiCheckboxSelection": boolean;
        /**
          * (optional) Enables multiple tree items selection
         */
        "multiSelection": boolean;
        /**
          * (optional) The default size of all tree items
         */
        "size": 'condensed' | 'large' | 'standard';
    }
    interface ModusTreeViewItem {
        /**
          * (optional) Checked state of the tree item
         */
        "checked": boolean;
        /**
          * (optional) Disables the tree item
         */
        "disabled": boolean;
        /**
          * (optional) Expanded state of the tree item
         */
        "expanded": boolean;
        /**
          * (optional) Checkbox indeterminate state of the tree item
         */
        "indeterminate": boolean;
        /**
          * (required) Label for the tree item
         */
        "label": string;
        "level": number;
        /**
          * (required) Unique tree item identifier
         */
        "nodeId": string;
        "options": TreeViewItemOptions;
        /**
          * (optional) Selected state of the tree item
         */
        "selected": boolean;
    }
}
export interface ModusAccordionItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusAccordionItemElement;
}
export interface ModusAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusAlertElement;
}
export interface ModusBreadcrumbCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusBreadcrumbElement;
}
export interface ModusButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusButtonElement;
}
export interface ModusCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusCheckboxElement;
}
export interface ModusChipCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusChipElement;
}
export interface ModusDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusDropdownElement;
}
export interface ModusFileDropzoneCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusFileDropzoneElement;
}
export interface ModusListItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusListItemElement;
}
export interface ModusModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusModalElement;
}
export interface ModusNavbarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusNavbarElement;
}
export interface ModusNavbarProfileMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusNavbarProfileMenuElement;
}
export interface ModusNumberInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusNumberInputElement;
}
export interface ModusPaginationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusPaginationElement;
}
export interface ModusRadioGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusRadioGroupElement;
}
export interface ModusSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusSelectElement;
}
export interface ModusSliderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusSliderElement;
}
export interface ModusSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusSwitchElement;
}
export interface ModusTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusTabsElement;
}
export interface ModusTextInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusTextInputElement;
}
export interface ModusToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusToastElement;
}
export interface ModusTreeViewItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLModusTreeViewItemElement;
}
declare global {
    interface HTMLModusAccordionElement extends Components.ModusAccordion, HTMLStencilElement {
    }
    var HTMLModusAccordionElement: {
        prototype: HTMLModusAccordionElement;
        new (): HTMLModusAccordionElement;
    };
    interface HTMLModusAccordionItemElement extends Components.ModusAccordionItem, HTMLStencilElement {
    }
    var HTMLModusAccordionItemElement: {
        prototype: HTMLModusAccordionItemElement;
        new (): HTMLModusAccordionItemElement;
    };
    interface HTMLModusAlertElement extends Components.ModusAlert, HTMLStencilElement {
    }
    var HTMLModusAlertElement: {
        prototype: HTMLModusAlertElement;
        new (): HTMLModusAlertElement;
    };
    interface HTMLModusBadgeElement extends Components.ModusBadge, HTMLStencilElement {
    }
    var HTMLModusBadgeElement: {
        prototype: HTMLModusBadgeElement;
        new (): HTMLModusBadgeElement;
    };
    interface HTMLModusBreadcrumbElement extends Components.ModusBreadcrumb, HTMLStencilElement {
    }
    var HTMLModusBreadcrumbElement: {
        prototype: HTMLModusBreadcrumbElement;
        new (): HTMLModusBreadcrumbElement;
    };
    interface HTMLModusButtonElement extends Components.ModusButton, HTMLStencilElement {
    }
    var HTMLModusButtonElement: {
        prototype: HTMLModusButtonElement;
        new (): HTMLModusButtonElement;
    };
    interface HTMLModusCardElement extends Components.ModusCard, HTMLStencilElement {
    }
    var HTMLModusCardElement: {
        prototype: HTMLModusCardElement;
        new (): HTMLModusCardElement;
    };
    interface HTMLModusCheckboxElement extends Components.ModusCheckbox, HTMLStencilElement {
    }
    var HTMLModusCheckboxElement: {
        prototype: HTMLModusCheckboxElement;
        new (): HTMLModusCheckboxElement;
    };
    interface HTMLModusChipElement extends Components.ModusChip, HTMLStencilElement {
    }
    var HTMLModusChipElement: {
        prototype: HTMLModusChipElement;
        new (): HTMLModusChipElement;
    };
    interface HTMLModusDropdownElement extends Components.ModusDropdown, HTMLStencilElement {
    }
    var HTMLModusDropdownElement: {
        prototype: HTMLModusDropdownElement;
        new (): HTMLModusDropdownElement;
    };
    interface HTMLModusFileDropzoneElement extends Components.ModusFileDropzone, HTMLStencilElement {
    }
    var HTMLModusFileDropzoneElement: {
        prototype: HTMLModusFileDropzoneElement;
        new (): HTMLModusFileDropzoneElement;
    };
    interface HTMLModusListElement extends Components.ModusList, HTMLStencilElement {
    }
    var HTMLModusListElement: {
        prototype: HTMLModusListElement;
        new (): HTMLModusListElement;
    };
    interface HTMLModusListItemElement extends Components.ModusListItem, HTMLStencilElement {
    }
    var HTMLModusListItemElement: {
        prototype: HTMLModusListItemElement;
        new (): HTMLModusListItemElement;
    };
    interface HTMLModusMessageElement extends Components.ModusMessage, HTMLStencilElement {
    }
    var HTMLModusMessageElement: {
        prototype: HTMLModusMessageElement;
        new (): HTMLModusMessageElement;
    };
    interface HTMLModusModalElement extends Components.ModusModal, HTMLStencilElement {
    }
    var HTMLModusModalElement: {
        prototype: HTMLModusModalElement;
        new (): HTMLModusModalElement;
    };
    interface HTMLModusNavbarElement extends Components.ModusNavbar, HTMLStencilElement {
    }
    var HTMLModusNavbarElement: {
        prototype: HTMLModusNavbarElement;
        new (): HTMLModusNavbarElement;
    };
    interface HTMLModusNavbarAppsMenuElement extends Components.ModusNavbarAppsMenu, HTMLStencilElement {
    }
    var HTMLModusNavbarAppsMenuElement: {
        prototype: HTMLModusNavbarAppsMenuElement;
        new (): HTMLModusNavbarAppsMenuElement;
    };
    interface HTMLModusNavbarMainMenuElement extends Components.ModusNavbarMainMenu, HTMLStencilElement {
    }
    var HTMLModusNavbarMainMenuElement: {
        prototype: HTMLModusNavbarMainMenuElement;
        new (): HTMLModusNavbarMainMenuElement;
    };
    interface HTMLModusNavbarNotificationsMenuElement extends Components.ModusNavbarNotificationsMenu, HTMLStencilElement {
    }
    var HTMLModusNavbarNotificationsMenuElement: {
        prototype: HTMLModusNavbarNotificationsMenuElement;
        new (): HTMLModusNavbarNotificationsMenuElement;
    };
    interface HTMLModusNavbarProfileMenuElement extends Components.ModusNavbarProfileMenu, HTMLStencilElement {
    }
    var HTMLModusNavbarProfileMenuElement: {
        prototype: HTMLModusNavbarProfileMenuElement;
        new (): HTMLModusNavbarProfileMenuElement;
    };
    interface HTMLModusNumberInputElement extends Components.ModusNumberInput, HTMLStencilElement {
    }
    var HTMLModusNumberInputElement: {
        prototype: HTMLModusNumberInputElement;
        new (): HTMLModusNumberInputElement;
    };
    interface HTMLModusPaginationElement extends Components.ModusPagination, HTMLStencilElement {
    }
    var HTMLModusPaginationElement: {
        prototype: HTMLModusPaginationElement;
        new (): HTMLModusPaginationElement;
    };
    interface HTMLModusProgressBarElement extends Components.ModusProgressBar, HTMLStencilElement {
    }
    var HTMLModusProgressBarElement: {
        prototype: HTMLModusProgressBarElement;
        new (): HTMLModusProgressBarElement;
    };
    interface HTMLModusRadioGroupElement extends Components.ModusRadioGroup, HTMLStencilElement {
    }
    var HTMLModusRadioGroupElement: {
        prototype: HTMLModusRadioGroupElement;
        new (): HTMLModusRadioGroupElement;
    };
    interface HTMLModusSelectElement extends Components.ModusSelect, HTMLStencilElement {
    }
    var HTMLModusSelectElement: {
        prototype: HTMLModusSelectElement;
        new (): HTMLModusSelectElement;
    };
    interface HTMLModusSliderElement extends Components.ModusSlider, HTMLStencilElement {
    }
    var HTMLModusSliderElement: {
        prototype: HTMLModusSliderElement;
        new (): HTMLModusSliderElement;
    };
    interface HTMLModusSpinnerElement extends Components.ModusSpinner, HTMLStencilElement {
    }
    var HTMLModusSpinnerElement: {
        prototype: HTMLModusSpinnerElement;
        new (): HTMLModusSpinnerElement;
    };
    interface HTMLModusSwitchElement extends Components.ModusSwitch, HTMLStencilElement {
    }
    var HTMLModusSwitchElement: {
        prototype: HTMLModusSwitchElement;
        new (): HTMLModusSwitchElement;
    };
    interface HTMLModusTabsElement extends Components.ModusTabs, HTMLStencilElement {
    }
    var HTMLModusTabsElement: {
        prototype: HTMLModusTabsElement;
        new (): HTMLModusTabsElement;
    };
    interface HTMLModusTextInputElement extends Components.ModusTextInput, HTMLStencilElement {
    }
    var HTMLModusTextInputElement: {
        prototype: HTMLModusTextInputElement;
        new (): HTMLModusTextInputElement;
    };
    interface HTMLModusToastElement extends Components.ModusToast, HTMLStencilElement {
    }
    var HTMLModusToastElement: {
        prototype: HTMLModusToastElement;
        new (): HTMLModusToastElement;
    };
    interface HTMLModusTooltipElement extends Components.ModusTooltip, HTMLStencilElement {
    }
    var HTMLModusTooltipElement: {
        prototype: HTMLModusTooltipElement;
        new (): HTMLModusTooltipElement;
    };
    interface HTMLModusTreeViewElement extends Components.ModusTreeView, HTMLStencilElement {
    }
    var HTMLModusTreeViewElement: {
        prototype: HTMLModusTreeViewElement;
        new (): HTMLModusTreeViewElement;
    };
    interface HTMLModusTreeViewItemElement extends Components.ModusTreeViewItem, HTMLStencilElement {
    }
    var HTMLModusTreeViewItemElement: {
        prototype: HTMLModusTreeViewItemElement;
        new (): HTMLModusTreeViewItemElement;
    };
    interface HTMLElementTagNameMap {
        "modus-accordion": HTMLModusAccordionElement;
        "modus-accordion-item": HTMLModusAccordionItemElement;
        "modus-alert": HTMLModusAlertElement;
        "modus-badge": HTMLModusBadgeElement;
        "modus-breadcrumb": HTMLModusBreadcrumbElement;
        "modus-button": HTMLModusButtonElement;
        "modus-card": HTMLModusCardElement;
        "modus-checkbox": HTMLModusCheckboxElement;
        "modus-chip": HTMLModusChipElement;
        "modus-dropdown": HTMLModusDropdownElement;
        "modus-file-dropzone": HTMLModusFileDropzoneElement;
        "modus-list": HTMLModusListElement;
        "modus-list-item": HTMLModusListItemElement;
        "modus-message": HTMLModusMessageElement;
        "modus-modal": HTMLModusModalElement;
        "modus-navbar": HTMLModusNavbarElement;
        "modus-navbar-apps-menu": HTMLModusNavbarAppsMenuElement;
        "modus-navbar-main-menu": HTMLModusNavbarMainMenuElement;
        "modus-navbar-notifications-menu": HTMLModusNavbarNotificationsMenuElement;
        "modus-navbar-profile-menu": HTMLModusNavbarProfileMenuElement;
        "modus-number-input": HTMLModusNumberInputElement;
        "modus-pagination": HTMLModusPaginationElement;
        "modus-progress-bar": HTMLModusProgressBarElement;
        "modus-radio-group": HTMLModusRadioGroupElement;
        "modus-select": HTMLModusSelectElement;
        "modus-slider": HTMLModusSliderElement;
        "modus-spinner": HTMLModusSpinnerElement;
        "modus-switch": HTMLModusSwitchElement;
        "modus-tabs": HTMLModusTabsElement;
        "modus-text-input": HTMLModusTextInputElement;
        "modus-toast": HTMLModusToastElement;
        "modus-tooltip": HTMLModusTooltipElement;
        "modus-tree-view": HTMLModusTreeViewElement;
        "modus-tree-view-item": HTMLModusTreeViewItemElement;
    }
}
declare namespace LocalJSX {
    interface ModusAccordion {
        /**
          * (optional) The accordion's aria-label.
         */
        "ariaLabel"?: string;
    }
    interface ModusAccordionItem {
        /**
          * (optional) Disables the accordion item, locks expand/collapse.
         */
        "disabled"?: boolean;
        /**
          * (optional) Whether the accordion item is expanded.
         */
        "expanded"?: boolean;
        /**
          * (required) The text to render in the header.
         */
        "headerText"?: string;
        /**
          * An event that fires on every accordion close.
         */
        "onClosed"?: (event: ModusAccordionItemCustomEvent<any>) => void;
        /**
          * An event that fires on every accordion open.
         */
        "onOpened"?: (event: ModusAccordionItemCustomEvent<any>) => void;
        /**
          * (optional) The size of accordion item.
         */
        "size"?: 'condensed' | 'standard';
    }
    interface ModusAlert {
        /**
          * (optional) The alert's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) Whether the alert has a dismiss button
         */
        "dismissible"?: boolean;
        /**
          * (optional) The alert message
         */
        "message"?: string;
        /**
          * An event that fires when the alert is dismissed
         */
        "onDismissClick"?: (event: ModusAlertCustomEvent<any>) => void;
        /**
          * (optional) The type of alert, sets the color and icon to render
         */
        "type"?: 'error' | 'info' | 'info-gray' | 'info-gray-dark' | 'success' | 'warning';
    }
    interface ModusBadge {
        /**
          * (optional) The badge's aria-label
         */
        "ariaLabel"?: string;
        /**
          * (optional) The color of the badge
         */
        "color"?: 'danger' | 'dark' | 'primary' | 'secondary' | 'success' | 'tertiary' | 'warning';
        /**
          * (optional) The size of the badge
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * (optional) The type of the badge
         */
        "type"?: 'counter' | 'default' | 'text';
    }
    interface ModusBreadcrumb {
        /**
          * The breadcrumb's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * The breadcrumbs to render.
         */
        "crumbs"?: Crumb[];
        /**
          * (optional) An event that fires on breadcrumb click.
         */
        "onCrumbClick"?: (event: ModusBreadcrumbCustomEvent<Crumb>) => void;
    }
    interface ModusButton {
        /**
          * (optional) The button's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) The style of the button
         */
        "buttonStyle"?: 'borderless' | 'fill' | 'outline';
        /**
          * (optional) The color of the button.
         */
        "color"?: 'danger' | 'default' | 'primary' | 'secondary' | 'warning';
        /**
          * (optional) Disables the button.
         */
        "disabled"?: boolean;
        /**
          * (optional) An event that fires on button click.
         */
        "onButtonClick"?: (event: ModusButtonCustomEvent<any>) => void;
        /**
          * (optional) The size of the button.
         */
        "size"?: 'small' | 'medium' | 'large';
    }
    interface ModusCard {
        /**
          * (optional) The card's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) The height of the card.
         */
        "height"?: string;
        /**
          * (optional) The width of the card.
         */
        "width"?: string;
    }
    interface ModusCheckbox {
        /**
          * (optional) The checkbox's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) Whether the checkbox is checked.
         */
        "checked"?: boolean;
        /**
          * (optional) Whether the checkbox is disabled.
         */
        "disabled"?: boolean;
        /**
          * (optional) Whether the checkbox is indeterminate.
         */
        "indeterminate"?: boolean;
        /**
          * (optional) The checkbox label.
         */
        "label"?: string;
        /**
          * An event that fires on checkbox click.
         */
        "onCheckboxClick"?: (event: ModusCheckboxCustomEvent<boolean>) => void;
        /**
          * (optional) The size of the button
         */
        "size"?: 'small' | 'medium';
    }
    interface ModusChip {
        /**
          * (optional) The chip's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) The chip's style.
         */
        "chipStyle"?: 'outline' | 'solid';
        /**
          * (optional) Whether the chip is disabled.
         */
        "disabled"?: boolean;
        /**
          * (optional) Whether the chip has an error.
         */
        "hasError"?: boolean;
        /**
          * (optional) The image's url.
         */
        "imageUrl"?: string;
        /**
          * An event that fires on chip click.
         */
        "onChipClick"?: (event: ModusChipCustomEvent<any>) => void;
        /**
          * An event that fires on close icon click.
         */
        "onCloseClick"?: (event: ModusChipCustomEvent<any>) => void;
        /**
          * (optional) Whether to show the checkmark.
         */
        "showCheckmark"?: boolean;
        /**
          * (optional) Whether to show the close icon.
         */
        "showClose"?: boolean;
        /**
          * (optional) The chip's size.
         */
        "size"?: 'medium' | 'large';
        /**
          * (optional) The chip's value.
         */
        "value"?: string;
    }
    interface ModusDropdown {
        /**
          * (optional) The dropdown's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) Disables the dropdown.
         */
        "disabled"?: boolean;
        /**
          * An event that fires on dropdown close.
         */
        "onDropdownClose"?: (event: ModusDropdownCustomEvent<any>) => void;
        /**
          * (optional) The placement of the dropdown in related to the toggleElement.
         */
        "placement"?: 'top' | 'right' | 'bottom' | 'left';
        /**
          * (required) The element id that the list renders near and that triggers the toggling of the list.
         */
        "toggleElementId"?: string;
    }
    interface ModusFileDropzone {
        /**
          * (optional) The dropzone's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) The dropzone's description text.
         */
        "description"?: string;
        /**
          * (optional) The dropzone's height.
         */
        "dropzoneHeight"?: string;
        /**
          * (optional) The dropzone's width.
         */
        "dropzoneWidth"?: string;
        /**
          * (optional) Whether to include the upload icon.
         */
        "includeStateIcon"?: boolean;
        /**
          * (optional) The dropzone's label text.
         */
        "label"?: string;
        /**
          * (optional) The dropzone's max file count.
         */
        "maxFileCount"?: number;
        /**
          * (optional) The dropzone's max file name length of each file.
         */
        "maxFileNameLength"?: number;
        /**
          * (optional) The dropzone's max total file size.
         */
        "maxTotalFileSizeBytes"?: number;
        /**
          * (optional) Whether multiple files can be uploaded.
         */
        "multiple"?: boolean;
        /**
          * An event that fires when files have been added or removed, regardless of whether they're valid.
         */
        "onFiles"?: (event: ModusFileDropzoneCustomEvent<[File[], string | null]>) => void;
    }
    interface ModusList {
    }
    interface ModusListItem {
        /**
          * (optional) Disables the list item
         */
        "disabled"?: boolean;
        /**
          * An event that fires on list item click
         */
        "onItemClick"?: (event: ModusListItemCustomEvent<any>) => void;
        /**
          * (optional) The selected state of the list item
         */
        "selected"?: boolean;
        /**
          * (optional) The size of list item
         */
        "size"?: 'condensed' | 'large' | 'standard';
        /**
          * (optional) The type of list item
         */
        "type"?: 'standard';
    }
    interface ModusMessage {
        /**
          * (optional) The message's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) The message's type.
         */
        "type"?: 'info' | 'question';
    }
    interface ModusModal {
        /**
          * (optional) The modal's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) The modal's primary button text.
         */
        "headerText"?: string;
        /**
          * An event that fires on modal close.
         */
        "onClosed"?: (event: ModusModalCustomEvent<any>) => void;
        /**
          * An event that fires on modal open.
         */
        "onOpened"?: (event: ModusModalCustomEvent<any>) => void;
        /**
          * An event that fires on primary button click.
         */
        "onPrimaryButtonClick"?: (event: ModusModalCustomEvent<any>) => void;
        /**
          * An event that fires on secondary button click.
         */
        "onSecondaryButtonClick"?: (event: ModusModalCustomEvent<any>) => void;
        /**
          * (optional) The modal's primary button text.
         */
        "primaryButtonText"?: string;
        /**
          * (optional) The modal's secondary button text.
         */
        "secondaryButtonText"?: string;
        /**
          * (optional) The modal's z-index.
         */
        "zIndex"?: string;
    }
    interface ModusNavbar {
        /**
          * (optional) The apps to render in the apps menu.
         */
        "apps"?: App[];
        /**
          * An event that fires on product logo click.
         */
        "onProductLogoClick"?: (event: ModusNavbarCustomEvent<MouseEvent>) => void;
        /**
          * An event that fires on profile menu sign out click.
         */
        "onProfileMenuSignOutClick"?: (event: ModusNavbarCustomEvent<MouseEvent>) => void;
        /**
          * (required) Product logo options.
         */
        "productLogoOptions"?: { height?: string; url: string };
        /**
          * (required) Profile menu options.
         */
        "profileMenuOptions"?: { avatarUrl?: string, email?: string, initials?: string, username: string };
        /**
          * (optional) Whether to display the navbar items in reverse order.
         */
        "reverse"?: boolean;
        /**
          * (optional) Whether to show the apps menu.
         */
        "showAppsMenu"?: boolean;
        /**
          * (optional) Whether to show the main menu.
         */
        "showMainMenu"?: boolean;
        /**
          * (optional) Whether to show notifications.
         */
        "showNotifications"?: boolean;
        /**
          * (optional) Whether to show the placeholder for Pendo.
         */
        "showPendoPlaceholder"?: boolean;
        /**
          * (optional) Whether to show search.
         */
        "showSearch"?: boolean;
        /**
          * (optional) Whether to show a shadow under the navbar.
         */
        "showShadow"?: boolean;
    }
    interface ModusNavbarAppsMenu {
        "apps"?: App[];
        "reverse"?: boolean;
    }
    interface ModusNavbarMainMenu {
    }
    interface ModusNavbarNotificationsMenu {
        "reverse"?: boolean;
    }
    interface ModusNavbarProfileMenu {
        "avatarUrl"?: string;
        "email"?: string;
        "initials"?: string;
        "onSignOutClick"?: (event: ModusNavbarProfileMenuCustomEvent<MouseEvent>) => void;
        "reverse"?: boolean;
        "username"?: string;
    }
    interface ModusNumberInput {
        /**
          * (optional) The input's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) Whether the input is disabled.
         */
        "disabled"?: boolean;
        /**
          * (optional) The input's error state text.
         */
        "errorText"?: string;
        /**
          * (optional) The input's helper text displayed below the input.
         */
        "helperText"?: string;
        /**
          * (optional) The input's label.
         */
        "label"?: string;
        /**
          * (optional) The input's maximum value.
         */
        "maxValue"?: number;
        /**
          * (optional) The input's minimum value.
         */
        "minValue"?: number;
        /**
          * An event that fires on input value change.
         */
        "onValueChange"?: (event: ModusNumberInputCustomEvent<string>) => void;
        /**
          * (optional) The input's placeholder text.
         */
        "placeholder"?: string;
        /**
          * (optional) Whether the input's content is read-only
         */
        "readOnly"?: boolean;
        /**
          * (optional) Whether the input is required.
         */
        "required"?: boolean;
        /**
          * (optional) The input's size.
         */
        "size"?: 'medium' | 'large';
        /**
          * (optional) The input's step.
         */
        "step"?: number;
        /**
          * (optional) The input's valid state text.
         */
        "validText"?: string;
        /**
          * (optional) The input's value.
         */
        "value"?: string;
    }
    interface ModusPagination {
        "activePage"?: number;
        "ariaLabel"?: string;
        "maxPage"?: number;
        "minPage"?: number;
        /**
          * An event that fires on page change.
         */
        "onPageChange"?: (event: ModusPaginationCustomEvent<number>) => void;
        "size"?: 'large' | 'medium' | 'small';
    }
    interface ModusProgressBar {
        /**
          * (optional) The progress bar's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) The progress bar's background color.
         */
        "backgroundColor"?: string;
        /**
          * (optional) The progress bar's foreground color.
         */
        "color"?: string;
        /**
          * (optional) The progress bar's maximum value.
         */
        "maxValue"?: number;
        /**
          * (optional) The progress bar's minimum value.
         */
        "minValue"?: number;
        /**
          * (optional) The progress bar's size.
         */
        "size"?: 'default' | 'compact';
        /**
          * (optional) The text displayed on the progress bar.
         */
        "text"?: string;
        /**
          * (optional) The progress bar's text color.
         */
        "textColor"?: string;
        /**
          * (optional) The progress bar's value.
         */
        "value"?: number;
    }
    interface ModusRadioGroup {
        /**
          * The radio group's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * The ID of the checked radio button.
         */
        "checkedId"?: string;
        /**
          * The radio button group name.
         */
        "name"?: string;
        /**
          * Fires on radio button click.
         */
        "onButtonClick"?: (event: ModusRadioGroupCustomEvent<string>) => void;
        /**
          * The radio buttons to render.
         */
        "radioButtons"?: RadioButton[];
    }
    interface ModusSelect {
        /**
          * (optional) The select's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) Whether the input is disabled.
         */
        "disabled"?: boolean;
        /**
          * (optional) The input's error text.
         */
        "errorText"?: string;
        /**
          * (optional) The input's helper text.
         */
        "helperText"?: string;
        /**
          * (optional) The input label.
         */
        "label"?: string;
        /**
          * An event that fires on input value change.
         */
        "onValueChange"?: (event: ModusSelectCustomEvent<unknown>) => void;
        /**
          * The options for the dropdown list.
         */
        "options"?: unknown[];
        /**
          * The options property to render in the dropdown list.
         */
        "optionsDisplayProp"?: string;
        /**
          * (optional) Whether the input is required.
         */
        "required"?: boolean;
        /**
          * (optional) The input's size.
         */
        "size"?: 'medium' | 'large';
        /**
          * (optional) The input's valid text.
         */
        "validText"?: string;
        /**
          * (optional) The input value.
         */
        "value"?: unknown;
    }
    interface ModusSlider {
        /**
          * (optional) The slider's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) Whether the slider is disabled. *
         */
        "disabled"?: boolean;
        /**
          * (optional) The slider's label.
         */
        "label"?: string;
        /**
          * (optional) The slider's maximum value.
         */
        "maxValue"?: number;
        /**
          * (optional) The slider's minimum value.
         */
        "minValue"?: number;
        /**
          * An event that fires on slider value change.
         */
        "onValueChange"?: (event: ModusSliderCustomEvent<string>) => void;
        /**
          * An event that fires on slider value input.
         */
        "onValueInput"?: (event: ModusSliderCustomEvent<string>) => void;
        /**
          * (optional) The slider's value.
         */
        "value"?: string;
    }
    interface ModusSpinner {
        /**
          * (optional) The color of the spinner in hex format (eg #FFFFFF)
         */
        "color"?: string;
        /**
          * (optional) The size of the spinner, will be applied to both the height and width
         */
        "size"?: string;
    }
    interface ModusSwitch {
        /**
          * (optional) The switch's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) Whether the switch is checked.
         */
        "checked"?: boolean;
        /**
          * (optional) Whether the switch is disabled.
         */
        "disabled"?: boolean;
        /**
          * (optional) The switch label.
         */
        "label"?: string;
        /**
          * An event that fires on switch click.
         */
        "onSwitchClick"?: (event: ModusSwitchCustomEvent<boolean>) => void;
    }
    interface ModusTabs {
        "ariaLabel"?: string;
        /**
          * An event that fires on tab change.
         */
        "onTabChange"?: (event: ModusTabsCustomEvent<string>) => void;
        "size"?: 'medium' | 'small';
        /**
          * The tabs to render.
         */
        "tabs"?: Tab[];
    }
    interface ModusTextInput {
        /**
          * (optional) The input's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) Whether the input has a clear button.
         */
        "clearable"?: boolean;
        /**
          * (optional) Whether the input is disabled.
         */
        "disabled"?: boolean;
        /**
          * (optional) The input's error state text.
         */
        "errorText"?: string;
        /**
          * (optional) The input's helper text displayed below the input.
         */
        "helperText"?: string;
        /**
          * (optional) Whether the search icon is included.
         */
        "includeSearchIcon"?: boolean;
        /**
          * (optional) The input's inputmode.
         */
        "inputmode"?: 'decimal' | 'email' | 'numeric' | 'search' | 'tel' | 'text' | 'url';
        /**
          * (optional) The input's label.
         */
        "label"?: string;
        /**
          * (optional) The input's maximum length.
         */
        "maxLength"?: number;
        /**
          * (optional) The input's minimum length.
         */
        "minLength"?: number;
        /**
          * An event that fires on input value change.
         */
        "onValueChange"?: (event: ModusTextInputCustomEvent<string>) => void;
        /**
          * (optional) The input's placeholder text.
         */
        "placeholder"?: string;
        /**
          * (optional) Whether the input's content is read-only
         */
        "readOnly"?: boolean;
        /**
          * (optional) Whether the input is required.
         */
        "required"?: boolean;
        /**
          * (optional) The input's size.
         */
        "size"?: 'medium' | 'large';
        /**
          * (optional) The input's type.
         */
        "type"?: 'text' | 'password';
        /**
          * (optional) The input's valid state text.
         */
        "validText"?: string;
        /**
          * (optional) The input's value.
         */
        "value"?: string;
    }
    interface ModusToast {
        /**
          * (optional) The toast's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) Whether the toast has a dismiss button.
         */
        "dismissible"?: boolean;
        /**
          * An event that fires when the toast is dismissed
         */
        "onDismissClick"?: (event: ModusToastCustomEvent<any>) => void;
        /**
          * (optional) Whether to show the toasts' icon.
         */
        "showIcon"?: boolean;
        /**
          * (optional) The toasts' type.
         */
        "type"?: 'danger' | 'dark' | 'default' | 'primary' | 'secondary' | 'success' | 'tertiary' | 'warning';
    }
    interface ModusTooltip {
        /**
          * (optional) The tooltip's aria-label.
         */
        "ariaLabel"?: string;
        /**
          * (optional) The tooltip's position relative to its content.
         */
        "position"?: 'bottom' | 'left' | 'right' | 'top';
        /**
          * The tooltip's text.
         */
        "text"?: string;
    }
    interface ModusTreeView {
        /**
          * (optional) Enables checkbox selection on each tree item
         */
        "checkboxSelection"?: boolean;
        /**
          * (optional) Disables each tree item
         */
        "disabled"?: boolean;
        /**
          * (optional) Enables multiple checkbox selection
         */
        "multiCheckboxSelection"?: boolean;
        /**
          * (optional) Enables multiple tree items selection
         */
        "multiSelection"?: boolean;
        /**
          * (optional) The default size of all tree items
         */
        "size"?: 'condensed' | 'large' | 'standard';
    }
    interface ModusTreeViewItem {
        /**
          * (optional) Checked state of the tree item
         */
        "checked"?: boolean;
        /**
          * (optional) Disables the tree item
         */
        "disabled"?: boolean;
        /**
          * (optional) Expanded state of the tree item
         */
        "expanded"?: boolean;
        /**
          * (optional) Checkbox indeterminate state of the tree item
         */
        "indeterminate"?: boolean;
        /**
          * (required) Label for the tree item
         */
        "label": string;
        "level"?: number;
        /**
          * (required) Unique tree item identifier
         */
        "nodeId": string;
        /**
          * An event that fires on tree item checkbox click
         */
        "onCheckboxClick"?: (event: ModusTreeViewItemCustomEvent<boolean>) => void;
        "onItemAdded"?: (event: ModusTreeViewItemCustomEvent<HTMLElement>) => void;
        /**
          * An event that fires on tree item click
         */
        "onItemClick"?: (event: ModusTreeViewItemCustomEvent<boolean>) => void;
        /**
          * An event that fires on tree item expand/collapse
         */
        "onItemExpandToggle"?: (event: ModusTreeViewItemCustomEvent<boolean>) => void;
        "options"?: TreeViewItemOptions;
        /**
          * (optional) Selected state of the tree item
         */
        "selected"?: boolean;
    }
    interface IntrinsicElements {
        "modus-accordion": ModusAccordion;
        "modus-accordion-item": ModusAccordionItem;
        "modus-alert": ModusAlert;
        "modus-badge": ModusBadge;
        "modus-breadcrumb": ModusBreadcrumb;
        "modus-button": ModusButton;
        "modus-card": ModusCard;
        "modus-checkbox": ModusCheckbox;
        "modus-chip": ModusChip;
        "modus-dropdown": ModusDropdown;
        "modus-file-dropzone": ModusFileDropzone;
        "modus-list": ModusList;
        "modus-list-item": ModusListItem;
        "modus-message": ModusMessage;
        "modus-modal": ModusModal;
        "modus-navbar": ModusNavbar;
        "modus-navbar-apps-menu": ModusNavbarAppsMenu;
        "modus-navbar-main-menu": ModusNavbarMainMenu;
        "modus-navbar-notifications-menu": ModusNavbarNotificationsMenu;
        "modus-navbar-profile-menu": ModusNavbarProfileMenu;
        "modus-number-input": ModusNumberInput;
        "modus-pagination": ModusPagination;
        "modus-progress-bar": ModusProgressBar;
        "modus-radio-group": ModusRadioGroup;
        "modus-select": ModusSelect;
        "modus-slider": ModusSlider;
        "modus-spinner": ModusSpinner;
        "modus-switch": ModusSwitch;
        "modus-tabs": ModusTabs;
        "modus-text-input": ModusTextInput;
        "modus-toast": ModusToast;
        "modus-tooltip": ModusTooltip;
        "modus-tree-view": ModusTreeView;
        "modus-tree-view-item": ModusTreeViewItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "modus-accordion": LocalJSX.ModusAccordion & JSXBase.HTMLAttributes<HTMLModusAccordionElement>;
            "modus-accordion-item": LocalJSX.ModusAccordionItem & JSXBase.HTMLAttributes<HTMLModusAccordionItemElement>;
            "modus-alert": LocalJSX.ModusAlert & JSXBase.HTMLAttributes<HTMLModusAlertElement>;
            "modus-badge": LocalJSX.ModusBadge & JSXBase.HTMLAttributes<HTMLModusBadgeElement>;
            "modus-breadcrumb": LocalJSX.ModusBreadcrumb & JSXBase.HTMLAttributes<HTMLModusBreadcrumbElement>;
            "modus-button": LocalJSX.ModusButton & JSXBase.HTMLAttributes<HTMLModusButtonElement>;
            "modus-card": LocalJSX.ModusCard & JSXBase.HTMLAttributes<HTMLModusCardElement>;
            "modus-checkbox": LocalJSX.ModusCheckbox & JSXBase.HTMLAttributes<HTMLModusCheckboxElement>;
            "modus-chip": LocalJSX.ModusChip & JSXBase.HTMLAttributes<HTMLModusChipElement>;
            "modus-dropdown": LocalJSX.ModusDropdown & JSXBase.HTMLAttributes<HTMLModusDropdownElement>;
            "modus-file-dropzone": LocalJSX.ModusFileDropzone & JSXBase.HTMLAttributes<HTMLModusFileDropzoneElement>;
            "modus-list": LocalJSX.ModusList & JSXBase.HTMLAttributes<HTMLModusListElement>;
            "modus-list-item": LocalJSX.ModusListItem & JSXBase.HTMLAttributes<HTMLModusListItemElement>;
            "modus-message": LocalJSX.ModusMessage & JSXBase.HTMLAttributes<HTMLModusMessageElement>;
            "modus-modal": LocalJSX.ModusModal & JSXBase.HTMLAttributes<HTMLModusModalElement>;
            "modus-navbar": LocalJSX.ModusNavbar & JSXBase.HTMLAttributes<HTMLModusNavbarElement>;
            "modus-navbar-apps-menu": LocalJSX.ModusNavbarAppsMenu & JSXBase.HTMLAttributes<HTMLModusNavbarAppsMenuElement>;
            "modus-navbar-main-menu": LocalJSX.ModusNavbarMainMenu & JSXBase.HTMLAttributes<HTMLModusNavbarMainMenuElement>;
            "modus-navbar-notifications-menu": LocalJSX.ModusNavbarNotificationsMenu & JSXBase.HTMLAttributes<HTMLModusNavbarNotificationsMenuElement>;
            "modus-navbar-profile-menu": LocalJSX.ModusNavbarProfileMenu & JSXBase.HTMLAttributes<HTMLModusNavbarProfileMenuElement>;
            "modus-number-input": LocalJSX.ModusNumberInput & JSXBase.HTMLAttributes<HTMLModusNumberInputElement>;
            "modus-pagination": LocalJSX.ModusPagination & JSXBase.HTMLAttributes<HTMLModusPaginationElement>;
            "modus-progress-bar": LocalJSX.ModusProgressBar & JSXBase.HTMLAttributes<HTMLModusProgressBarElement>;
            "modus-radio-group": LocalJSX.ModusRadioGroup & JSXBase.HTMLAttributes<HTMLModusRadioGroupElement>;
            "modus-select": LocalJSX.ModusSelect & JSXBase.HTMLAttributes<HTMLModusSelectElement>;
            "modus-slider": LocalJSX.ModusSlider & JSXBase.HTMLAttributes<HTMLModusSliderElement>;
            "modus-spinner": LocalJSX.ModusSpinner & JSXBase.HTMLAttributes<HTMLModusSpinnerElement>;
            "modus-switch": LocalJSX.ModusSwitch & JSXBase.HTMLAttributes<HTMLModusSwitchElement>;
            "modus-tabs": LocalJSX.ModusTabs & JSXBase.HTMLAttributes<HTMLModusTabsElement>;
            "modus-text-input": LocalJSX.ModusTextInput & JSXBase.HTMLAttributes<HTMLModusTextInputElement>;
            "modus-toast": LocalJSX.ModusToast & JSXBase.HTMLAttributes<HTMLModusToastElement>;
            "modus-tooltip": LocalJSX.ModusTooltip & JSXBase.HTMLAttributes<HTMLModusTooltipElement>;
            "modus-tree-view": LocalJSX.ModusTreeView & JSXBase.HTMLAttributes<HTMLModusTreeViewElement>;
            "modus-tree-view-item": LocalJSX.ModusTreeViewItem & JSXBase.HTMLAttributes<HTMLModusTreeViewItemElement>;
        }
    }
}
