name: Add Issues to Modus project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/trimble-oss/projects/5
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
