name: Google Chat Notification
on:
  pull_request:
    types: [opened, reopened, closed]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Google Chat Notification
      uses: trimble-oss/gh-actions/google-chat-notification@main
      with:
        url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
