name: google-chat-notify
on:
  pull_request:
    types: [opened, reopened, closed]
  pull_request_review_comment:
    types: [created]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Google Chat Notification
      uses: CommonMarvel/google-chat-notification@v1.2.1
      with:
        url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
