name: 'Issue Labeler'
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'coliff' && github.actor != 'ElishaSamPeterPrabhu' && github.actor != 'HarshithaNous' && github.actor != 'mitch-trimble' && github.actor != 'prashanth-offcl' && github.actor != 'prashanthr6383' }}
    steps:
      - uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
        with:
          configuration-path: .github/issue-labeler.yml
          enable-versioned-regex: 0
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
