name: 'Check spelling'
on:
  pull_request:
    branches-ignore:
      - "dependabot/**"

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
        with:
          inline: warning
          strict: false
          incremental_files_only: true
